apiVersion: apps/v1
kind: Deployment
metadata:
  name: descheduler
  namespace: kube-system
  labels:
    app: descheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: descheduler
  template:
    metadata:
      labels:
        app: descheduler
    spec:
      containers:
        - name: descheduler
          image: k8s.gcr.io/descheduler/descheduler:v0.21.0
          command:
            - /descheduler
          args:
            - --v=3
          resources:
            {}
          volumeMounts:
            - mountPath: /policy-dir
              name: policy-volume
      volumes:
        - name: policy-volume
          configMap:
            name: descheduler-policy-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: default
        pluginConfig:
        - name: "RemovePodsViolatingTopologySpreadConstraint"
          args:
            includeSoftConstraints: false
        plugins:
          balance:
            enabled:
            - "RemovePodsViolatingTopologySpreadConstraint"
