apiVersion: apps/v1
kind: Deployment
metadata:
  name: descheduler
  namespace: kube-system
  labels:
    app: descheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: descheduler
  template:
    metadata:
      labels:
        app: descheduler
    spec:
      containers:
        - name: descheduler
          image: k8s.gcr.io/descheduler/descheduler:v0.21.0
          command:
            - /descheduler
          args:
            - --v=3
            - --policy-config-file=/policy-dir/policy.yaml
            - --kubeconfig=/path/to/kubeconfig
          resources:
            {}
          volumeMounts:
            - mountPath: /policy-dir
              name: policy-volume
          env:
            - name: "POD_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: policy-volume
          configMap:
            name: descheduler-policy-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    strategies:
      "RemovePodsViolatingTopologySpreadConstraint":
        enabled: true
        params:
          includeSoftConstraints: false
